### ISSUE TITLE
audio-responses directory?

### ISSUE THREAD

**Issue by joech4n** [Apipa169/Assistant-Relay-Docker#5]
Hi! I am trying to run this in docker and am not sure where to get "audio-responses" directory for:

```
docker run -d --name assistant_relay \
-p 3000:3000 \
-v /path/to/volume/config.json:/assistant_relay/bin/config.json:rw \
-v /path/to/volume/audio-responses:/assistant_relay/bin/audio-responses:rw \
apipa169/assistant-relay:latest
```

Can you shed some light on what that is for or from?

I am wondering if it's causing my error because of missing files:

<details>
  <summary>expand log</summary>

```
2020-10-12T06:20:54.597896300Z [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
2020-10-12T06:20:54.851526100Z [PM2] PM2 Successfully daemonized
2020-10-12T06:20:54.875318200Z [PM2] Starting /assistant_relay/bin/www in fork_mode (1 instance)
2020-10-12T06:20:54.896416500Z [PM2] Done.
2020-10-12T06:20:54.930126700Z ┌─────┬────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
2020-10-12T06:20:54.930154800Z │ id  │ name   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
2020-10-12T06:20:54.930159500Z ├─────┼────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
2020-10-12T06:20:54.930163300Z │ 0   │ www    │ default     │ 3.2.0   │ fork    │ 52       │ 0s     │ 0    │ online    │ 0%       │ 31.0mb   │ root     │ disabled │
2020-10-12T06:20:54.930166500Z └─────┴────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
2020-10-12T06:20:55.293139800Z [TAILING] Tailing last 15 lines for [www] process (change the value with --lines option)
2020-10-12T06:20:55.300607200Z /root/.pm2/logs/www-out.log last 15 lines:
2020-10-12T06:20:55.301310500Z /root/.pm2/logs/www-error.log last 15 lines:
2020-10-12T06:20:55.618099500Z 0|www  | Error: EISDIR: illegal operation on a directory, read
2020-10-12T06:20:55.618238900Z 0|www  |     at Object.readSync (fs.js:577:3)
2020-10-12T06:20:55.618249100Z 0|www  |     at tryReadSync (fs.js:353:20)
2020-10-12T06:20:55.618252600Z 0|www  |     at readFileSync (fs.js:390:19)
2020-10-12T06:20:55.618277400Z 0|www  |     at FileSync.read (/assistant_relay/node_modules/lowdb/adapters/FileSync.js:35:22)
2020-10-12T06:20:55.618282100Z 0|www  |     at LodashWrapper.db.read (/assistant_relay/node_modules/lowdb/lib/main.js:32:21)
2020-10-12T06:20:55.618378900Z 0|www  |     at module.exports (/assistant_relay/node_modules/lowdb/lib/main.js:51:13)
2020-10-12T06:20:55.618691000Z 0|www  |     at /assistant_relay/helpers/server.js:21:26
2020-10-12T06:20:55.618726400Z 0|www  |     at new Promise (<anonymous>)
2020-10-12T06:20:55.618744100Z 0|www  |     at exports.initializeServer (/assistant_relay/helpers/server.js:20:12)
2020-10-12T06:20:55.618747600Z 0|www  |     at /assistant_relay/app.js:31:11 {
2020-10-12T06:20:55.618750400Z 0|www  |   errno: -21,
2020-10-12T06:20:55.618753200Z 0|www  |   syscall: 'read',
2020-10-12T06:20:55.618755800Z 0|www  |   code: 'EISDIR'
2020-10-12T06:20:55.618758500Z 0|www  | }
2020-10-12T06:20:55.620546200Z 0|www  | Error: EISDIR: illegal operation on a directory, read
2020-10-12T06:20:55.620564900Z 0|www  |     at Object.readSync (fs.js:577:3)
2020-10-12T06:20:55.620569300Z 0|www  |     at tryReadSync (fs.js:353:20)
2020-10-12T06:20:55.620572200Z 0|www  |     at readFileSync (fs.js:390:19)
2020-10-12T06:20:55.620575000Z 0|www  |     at FileSync.read (/assistant_relay/node_modules/lowdb/adapters/FileSync.js:35:22)
2020-10-12T06:20:55.620577900Z 0|www  |     at LodashWrapper.db.read (/assistant_relay/node_modules/lowdb/lib/main.js:32:21)
2020-10-12T06:20:55.620581400Z 0|www  |     at module.exports (/assistant_relay/node_modules/lowdb/lib/main.js:51:13)
2020-10-12T06:20:55.620584500Z 0|www  |     at /assistant_relay/bin/www:12:20
2020-10-12T06:20:55.620587200Z 0|www  |     at Object.<anonymous> (/assistant_relay/bin/www:55:3)
2020-10-12T06:20:55.620590500Z 0|www  |     at Module._compile (internal/modules/cjs/loader.js:1200:30)
2020-10-12T06:20:55.620666000Z 0|www  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
2020-10-12T06:20:55.620673500Z 0|www  |   errno: -21,
2020-10-12T06:20:55.620676300Z 0|www  |   syscall: 'read',
2020-10-12T06:20:55.620678900Z 0|www  |   code: 'EISDIR'
2020-10-12T06:20:55.620681700Z 0|www  | }
```

</details>

FWIW, I'm running `docker run -d --name assistant_relay -p 3000:3000 -v config.json:/assistant_relay/bin/config.json:rw -v audio-responses:/assistant_relay/bin/audio-responses:rw apipa169/assistant-relay:latest`, and my current working directory looks like:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/11/2020  11:07 PM                audio-responses
-a----        10/11/2020  10:49 PM             23 config.json
```

**Comment by Apipa169** [comment]
If a request is made to Google it returns audio. This is usually something like "Ok, broadcasting now". These audio responses can be played from the frontend. To make sure they are still there after restarting the container you can mount the folder. But it is not required. It only gives an error in the frontend when you try to play a file which does not exist anymore.
