### ISSUE TITLE
'Required port not given'

### ISSUE THREAD

**Issue by seanmccabe** [Apipa169/Assistant-Relay-Docker#7]
Getting an error when trying to deploy the beta version:

`/assistant-relay/node_modules/bonjour/lib/service.js:18
  if (!opts.port) throw new Error('Required port not given')
                  ^
Error: Required port not given
    at new Service (/assistant-relay/node_modules/bonjour/lib/service.js:18:25)
    at Registry.publish (/assistant-relay/node_modules/bonjour/lib/registry.js:18:17)
    at Bonjour.publish (/assistant-relay/node_modules/bonjour/index.js:16:25)
    at Server.<anonymous> (/assistant-relay/server/index.js:97:29)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:326:22)
    at Server.EventEmitter.emit (domain.js:486:12)
    at emitListeningNT (net.js:1351:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-relay@4.0.0 dev: `babel-node server/index.js `
npm ERR! Exit status 1
npm ERR! Failed at the assistant-relay@4.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-21T21_22_23_784Z-debug.log`

Showing as running but it is not.

**Comment by Backslashh** [comment]
I get the same.

**Comment by r1chjames** [comment]
On the latest stable release, the provided docker command works (assuming the config.json is correct and in-place). In the latest beta version I get the same error as @seanmccabe (except for changing the underscore in `assistant_relay` for a hyphen (i.e. `assistant-relay`).

**Comment by seanmccabe** [comment]
All resolved.
